### ISSUE TITLE
No such file or directory on remote machine

### ISSUE THREAD

**Issue by zaeemnalla** [xxh/xxh-plugin-zsh-ohmyzsh#2]
Is this plugin meant to create these directories or is it an issue with xxh instead?

```
source xxh.zsh +if +q cloud-desktop
[oh-my-zsh] plugin 'zsh-apple-touchbar' not found
[oh-my-zsh] plugin 'zsh-autosuggestions' not found
[oh-my-zsh] plugin 'zsh-syntax-highlighting' not found
[oh-my-zsh] autojump not found. Please install it first.
Starting ssh-agent...
_start_agent:6: no such file or directory: /local/home/username/.xxh/.ssh/environment-hostname
chmod: cannot access `/local/home/username/.xxh/.ssh/environment-hostname': No such file or directory
_start_agent:.:8: no such file or directory: /local/home/username/.xxh/.ssh/environment-hostname
/home/username/.xxh/.xxh/plugins/xxh-plugin-zsh-ohmyzsh/build/ohmyzsh/oh-my-zsh.sh:source:125: no such file or directory: /home/username/.xxh/.xxh/plugins/xxh-plugin-zsh-ohmyzsh/build/ohmyzsh/themes/powerlevel10k/powerlevel10k.zsh-theme
```

**Comment by anki-code** [comment]
Hello @zaeemnalla!
1. What is your target host OS and what is your local OS?
2. Do you have additional settings? (maybe in the xxh config)

**Comment by Fongeme** [comment]
Hey, im getting the same, Ubuntu WSL -> CentOS 7, no additional settings afaik

**Comment by anki-code** [comment]
@Fongeme thanks for reporting this! I haven't WSL and CentOS now. So I'm asking additional info from you:

1. Are you have exactly the same output? If no please provide your output.
2. Add full info: xxh version, xxh-plugins installed (or any other modifications).
3. If it is possible add verbose log: `xxh myhost +if +v`.

**Comment by anki-code** [comment]
I've tested the plugin again in [xxh-dev](https://github.com/xxh/xxh-dev) environment and Ubuntu->CentOS have no exceptions:

![Screenshot_20201012_150940](https://user-images.githubusercontent.com/1708680/95744993-fd5b9080-0c9c-11eb-9633-9093590c8b3b.png)

Could it be related to WSL?

**Comment by Fongeme** [comment]
My response is a bit different, i'll attach it and let me know if you prefer me to open another issue(On another glance this could be because i've missed something but not sure):
```
source /home/yair/.local/bin/xxh.zsh <IP> +I xxh-plugin-zsh-ohmyzsh +if +q +v
yair@<IP>'s password:
[oh-my-zsh] plugin 'zsh-autosuggestions' not found
[oh-my-zsh] plugin 'zsh-syntax-highlighting' not found
/home/yair/.xxh/.xxh/plugins/xxh-plugin-zsh-ohmyzsh/build/ohmyzsh/oh-my-zsh.sh:source:128: no such file or directory: /home/yair/.xxh/.xxh/plugins/xxh-plugin-zsh-ohmyzsh/build/ohmyzsh/themes/powerlevel10k/powerlevel10k.zsh-theme
localhost%
```

**Comment by anki-code** [comment]
@Fongeme Please run on your home host (where you do `source`) and post here the output:
```
echo $ZSH_THEME
echo $plugins
```

**Comment by Fongeme** [comment]
```
powerlevel10k/powerlevel10k
git ubuntu colored-man-pages command-not-found web-search zsh-autosuggestions zsh-syntax-highlighting
```

**Comment by anki-code** [comment]
Got it. You've got "not found" warnings because you have additional plugins in your OMZ: `zsh-autosuggestions`, `zsh-syntax-highlighting`, `powerlevel10k`. But `xxh-plugin-zsh-ohmyzsh` built clean installation of OMZ.

What you need:
1. Fork this repository and rename to `xxh-plugin-zsh-ohmyzsh-Fongeme` for example.
2. Add installation of your additional plugins to `build.sh` script
3. After this you can install your pack of xxh OMZ: `xxh +R xxh-plugin-zsh-ohmyzsh +RI https://github.com/Fongeme/xxh-plugin-zsh-ohmyzsh-Fongeme`

**Comment by Fongeme** [comment]
Oh, i thought xxh had support for additional plugins aswell, maybe i could try supporting it in a pr, do you think it's viable?(Have yet to read the source code)

**Comment by anki-code** [comment]
1. First of all xxh has an [ideas behind](https://github.com/xxh/xxh/wiki#the-ideas-behind-xxh) and one of the idea:

> Careful. No blindfold copying config files from local to remote host. Following the privacy and repeatability reasons the better way is to fork the xxh plugin or shell example and pack your config to it.

The next idea is:

> Be open and fork-ready. Every repo could be forked, customized and reused without waiting for package management system, xxh releases or any third party.

As result the simple way for the user is just fork the repo and create own version with all lovely tools.

2. To support the installed themes/plugins you should read it from the zsh configs and install it in `build.sh` script. I don't know how much work is needed to make this process universal and how seamless the installation process will be. I'm just not the user of zsh/omz. PRs are welcome!

3. I'm going to close this issue because the first message of this issue has the same problem and the answer is here and above. Feel free to continue the thread.

**Comment by Fongeme** [comment]
Okay, following that note, we could have a config for xxh/omz so plugins could be added without having to rebuild, not necessarily grab them from the user environment, but make the xxh environment a bit more configurable(ofc if one wants to copy his configs, one should be able to if we follow that line of thought)

**Comment by anki-code** [comment]
Yeah, for example you can create `omz-plugins.txt` file in the repo and use it in `build.sh` as the list of packages to install.

**Comment by anki-code** [comment]
JFYI The start point to understanding how xxh works - https://github.com/xxh/xxh/wiki#how-it-works
